name: ChunkRevive
version: '26-Release.1'
main: github.freshchromatic.chunkrevive.bootstrap.ChunkRevivePlugin
api-version: '1.21'
authors:
  - FreshChromatic
  - tcib_cat
website: https://modrinth.com/plugin/chunkrevive
folia-supported: true
description: Make the chunk to its original state.

dependencies:
  server:
    FreshLib:
      load: BEFORE
      required: true
      join-classpath: true
    packetevents:
      load: BEFORE
      required: false
      join-classpath: true
    Residence:
      load: BEFORE
      required: false
      join-classpath: true

permissions:
  chunkrevive.admin:
    description: Access to all /cr admin commands
    default: op
  chunkrevive.keep:
    description: Access to /keepchunk chunk protection mode
    default: true
